version: '3.3'

services:
  node:
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    links: 
      - redis
    command: node --inspect index.js
  redis:
    image: redis:4-alpine