version: '2.1'

services:
  rnd-node:
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
    command: node --inspect app.js
  redis:
    image: redis:4-alpine